### ISSUE TITLE
Homeland 刚部署完，登录，注册，找回密码都不可用，都跳到主页无任何其他反应

### ISSUE THREAD

**Issue by pangguoming** [ruby-china/homeland#1404]
Homeland 刚部署完，登录，注册，找回密码都不可用，都跳到主页无任何其他反应

部署地址：
http://ai-helloworld.com/

求解

**Comment by pangguoming** [comment]
docker-compose.yml 修改如下：
```

web:
   ports:
     - '8060:80'

 caddy:
   ports:
     - '8061:80'
     - '8062:443'
```

**Comment by pangguoming** [comment]
app.config.env 修改如下：

```
RAILS_ENV=production
# RAILS_LOG_TO_STDOUT=true

# Database
DATABASE_URL=postgres://postgres:@postgresql:5432/homeland
# DATABASE_POOL=64
REDIS_URL=redis://redis:6379/1

# App Config
app_name=AI-helloworld
domain=ai-helloworld.com
admin_emails=xxxxxxx@yeah.net

mailer_provider=smtp
mailer_sender=xxxxxxxx@163.com
mailer_options_address=smtp.163.com
mailer_options_port=465
mailer_options_domain=163.com
mailer_options_user_name=xxxxxxxx@163.com
mailer_options_password=xxxxxxxxxxxx
mailer_options_authentication=login
mailer_options_enable_starttls_auto=true
```

**Comment by qichunren** [comment]
问题解决了吗？

**Comment by pangguoming** [comment]
> 问题解决了吗？

没

**Comment by qichunren** [comment]
我在你网站测试发现的的确是这样，但是注册数据是保存到数据库了。可能与https证书有关。你想办法这个配置好再试试。

**Comment by pangguoming** [comment]
> 我在你网站测试发现的的确是这样，但是注册数据是保存到数据库了。可能与https证书有关。你想办法这个配置好再试试。

能先关闭https 吗？ 不想花钱买证书

**Comment by pangguoming** [comment]
对了，我是 已经安装了nginx，代理了 homeland 在docker中的nginx

**Comment by pangguoming** [comment]
我在 docker这配置如下
```
web:
   ports:
     - '8060:80'

 caddy:
   ports:
     - '8061:80'
     - '8062:443'
```
我已经安装的nginx 指向了8060
