### ISSUE TITLE
页面变窄后，header中logo与导航重叠

### ISSUE THREAD

**Issue by renyijiu** [ruby-china/homeland#899]
![图片](https://ooo.0o0.ooo/2017/03/16/58ca702ea17c3.png)

如图中显示，Firefox和chrome是存在这个问题的，
我试了下，大概改成-20px左右差不多
```css
@media (max-width: 767px) {
    .navbar-header {
      text-align: center;
      padding: 0;
margin-bottom: -20px;
......
    }
}
```
